<?xml version="1.0"?>
<package format="2">
  <name>cu_logitech_quickcam</name>
  <version>0.1.0</version>
  <description>The cu_logitech_quickcam package</description>
  <maintainer email="migoerner@constructor.university">Michael Goerner</maintainer>
  <license>BSD</license>

  <exec_depend>image_proc</exec_depend>
  <exec_depend>usb_cam</exec_depend>
  <buildtool_depend>catkin</buildtool_depend>
</package>
